### ISSUE TITLE
Pipeline statements do not get variables from env

### ISSUE THREAD

**Issue by kevlarjacket** [jenkinsci/codescene-plugin#22]
Using a declarative pipeline with Version 1.5.1 of the plugin:

```
                stage("codescene"){
                    agent {label 'codescene-agent'}
                    steps('step_1'){
                        script{
                            sh 'echo $GIT_COMMIT'
                            result = codescene analyzeBranchDiff: true,
                                         baseRevision: 'origin/master',
                                         credentialsId: 'creds-hash',
                                         deltaAnalysisUrl: 'http://hostname:3003/projects/3/delta-analysis',
                                         failOnDecliningCodeHealth: false,
                                         failOnFailedGoal: false,
                                         markBuildAsUnstable: true,
                                         originUrl: 'http://hostname:7990/bitbucket/projects/my_proj/repos/my_repo/browse',
                                         repository: 'my_repo' ,
                                         useBiomarkers: false
                            echo result
                            echo "Finish Stage 'Codescene'"
                        }
                    }
                }
```

This snippet yields the following output: 
```
+ echo abcd1234
abcd1234

java.lang.IllegalArgumentException: A commit hash cannot be null!
        at org.jenkinsci.plugins.codescene.Domain.Commit.<init>(Commit.java:13)
        at org.jenkinsci.plugins.codescene.CodeSceneBuilder.perform(CodeSceneBuilder.java:348)
        at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
        at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
        at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```
I believe this is because the [env variables are not being loaded correctly](https://github.com/jenkinsci/codescene-plugin/blob/master/src/main/java/org/jenkinsci/plugins/codescene/CodeSceneBuilder.java#L348).

**Comment by panzo** [comment]
Hi @kevlarjacket there is a new release, in case of pipeline config the env are fetched from the workflow last execution step.

**Comment by kevlarjacket** [comment]
Thanks @panzo, this issue is fixed in the new release.
