### ISSUE TITLE
org.glassfish.json.JsonArrayBuilderImpl$JsonArrayImpl cannot be cast to javax.json.JsonString

### ISSUE THREAD

**Issue by kevlarjacket** [jenkinsci/codescene-plugin#26]
### Version report

Plugin version 1.5.2

### Reproduction steps

One specific commit is causing a failure of the codescene delta analysis job. I have tried to narrow down what is unique about the commit that is causing the failure, but so far it looks like a normal commit; several new files are added and existing files modified. 

According to the stack trace, **this line is the culprit** though: https://github.com/jenkinsci/codescene-plugin/blob/8cf9eb57694ef156fb7ea134be79b03a3bc67733/src/main/java/org/jenkinsci/plugins/codescene/Domain/ReviewOfNewFile.java#L35

Let me know if I can provide some information about the commit that might be relevant. 
### Results

Expected result:

Delta Analysis should succeed, and stage should pass.

Actual result:

Logs show that the Internal Delta Analysis succeeded:

```
2021-05-31 17:12:49.882 9f74f828566c worker-1 INFO [cacsremoteservice.restapi.delta-analysis:172] - Delta analysis requested for project ID 65 with valid commit range: ["c1a97b620eac771e27c11674de77338c5089d789"] for repository util resolved to /codescene/repos/9d9de7aac264558e7a861cbafd88436ca91243bb/util
2021-05-31 17:12:49.885 9f74f828566c worker-1 INFO [cacsremoteservice.restapi.delta-analysis:79] - Delta analysis on results in  /codescene/analysis/e360f5a7fd0f5b6fed8120c4e2bea0513f6b11fa/analysis20210530181818  for the commits  ["c1a97b620eac771e27c11674de77338c5089d789"]  using Git:  git
2021-05-31 17:12:49.886 9f74f828566c worker-1 INFO [codescene.delta.delta-analysis:196] - Delta analysis: updating the repo /codescene/repos/9d9de7aac264558e7a861cbafd88436ca91243bb/util (received target: /codescene/repos/9d9de7aac264558e7a861cbafd88436ca91243bb/util)
2021-05-31 17:12:49.886 9f74f828566c worker-1 INFO [codescene.mining.evolution:33] - Updating the repo in /codescene/repos/9d9de7aac264558e7a861cbafd88436ca91243bb/util with 'git :reset' and remote branch pruning = false with submodules = false
2021-05-31 17:12:50.226 9f74f828566c worker-1 INFO [codescene.delta.delta-analysis:204] - Delta analysis: updated the repo /codescene/repos/9d9de7aac264558e7a861cbafd88436ca91243bb/util
2021-05-31 17:12:50.227 9f74f828566c worker-1 INFO [codescene.delta.delta-analysis:29] - Parse commits in /codescene/repos/9d9de7aac264558e7a861cbafd88436ca91243bb/util.
2021-05-31 17:12:50.239 9f74f828566c worker-1 INFO [codescene.delta.delta-analysis:41] - Parsed commits in /codescene/repos/9d9de7aac264558e7a861cbafd88436ca91243bb/util.
2021-05-31 17:12:50.240 9f74f828566c worker-1 INFO [codescene.delta.warnings:133] - Running detectors using the context:  
<redacted>
worker-1 INFO [codescene.delta.detectors.code-health:49] - Proceeding to check biomarkers for modified hotspots:  ("util/build_tools/buildcfg/gencfg.py")
2021-05-31 17:13:13.683 9f74f828566c worker-1 INFO [codescene.delta.detectors.goals:33] - Delta check of goal violation for the notes:  util/report_scripts/gen_mps_swb_sync_report.py
2021-05-31 17:13:13.684 9f74f828566c worker-1 INFO [codescene.delta.detectors.new-code:44] - Proceeding to check new code for the files:  ["util/build_tools/buildcfg/cfgware_gen.py" "util/toolbox/crc32.py" "util/toolbox/srec_tools/srec_writer.py"]
2021-05-31 17:13:15.339 9f74f828566c worker-1 INFO [codescene.risks.prediction:160] - Risk profile for repo  util  : considering  2000  commits out of a total of  1306
2021-05-31 17:13:15.356 9f74f828566c worker-1 INFO [codescene.delta.risk-classification:162] - Risk classification completed in repo = 
<redacted>
2021-05-31 17:13:15.370 9f74f828566c worker-1 INFO [cacsremoteservice.restapi.delta-analysis:71] - Delta analysis completed:  {:description "Be careful with the change -- it degrades the code health.", :improvements [] 
```

But the stage fails, with this stack trace in the jenkins console:
```
java.lang.ClassCastException: org.glassfish.json.JsonArrayBuilderImpl$JsonArrayImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:176)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:181)
	at org.jenkinsci.plugins.codescene.Domain.ReviewOfNewFile.parseReviewResultsFrom(ReviewOfNewFile.java:35)
	at org.jenkinsci.plugins.codescene.Domain.ReviewOfNewFile.<init>(ReviewOfNewFile.java:25)
	at org.jenkinsci.plugins.codescene.Domain.NewFiles.<init>(NewFiles.java:28)
	at org.jenkinsci.plugins.codescene.Domain.DeltaAnalysisResult.<init>(DeltaAnalysisResult.java:32)
	at org.jenkinsci.plugins.codescene.DeltaAnalysis.parseSuccessfulAnalysisResults(DeltaAnalysis.java:79)
	at org.jenkinsci.plugins.codescene.DeltaAnalysis.synchronousRequestWith(DeltaAnalysis.java:50)
	at org.jenkinsci.plugins.codescene.DeltaAnalysis.runOn(DeltaAnalysis.java:31)
	at org.jenkinsci.plugins.codescene.CodeSceneBuilder.runDeltaAnalysisOnBranchDiff(CodeSceneBuilder.java:282)
	at org.jenkinsci.plugins.codescene.CodeSceneBuilder.analyzeWorkOnBranchFor(CodeSceneBuilder.java:402)
	at org.jenkinsci.plugins.codescene.CodeSceneBuilder.perform(CodeSceneBuilder.java:377)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by panzo** [comment]
- there is a new release 1.5.4 with a fix for this issue

**Comment by kevlarjacket** [comment]
Thanks @panzo, confirmed the latest release does fix this issue.
